# Generated by Django 4.2.2 on 2023-08-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("DOA", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "postID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("posted_date", models.DateField(auto_now_add=True)),
                ("contents", models.TextField()),
                (
                    "authorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.users"
                    ),
                ),
            ],
        ),
    ]
